name: Build Firefly Desktop

on:
    workflow_dispatch:
        inputs:
            debugElectronBuilder:
                description: 'Verbose electron-builder output'
                required: true
                default: 'false'
            stage:
                description: 'Stage (alpha, beta, or prod)'
                required: true
                default: 'alpha'

jobs:
    setup:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/desktop')
        outputs:
            version: ${{ steps.set_outputs.outputs.version }}
            release_name: ${{ steps.set_outputs.outputs.release_name }}
            stage: ${{ steps.set_outputs.outputs.stage }}

        steps:
            - id: set_outputs
              name: Set outputs for version, release name, and stage
              run: |
                  VERSION=${GITHUB_REF#refs/*/desktop-}
                  RELEASE_NAME=$(echo $VERSION | perl -0777 -pe 's/^([0-9]\d*\.[0-9]\d*\.[0-9]\d*)(?:-([a-z]*)-(\d*))?$/$1 \u$2 $3/')
                  STAGE=$(echo $VERSION | perl -0777 -pe 's/^([0-9]\d*\.[0-9]\d*\.[0-9]\d*)(?:-([a-z]*)-([0-9]\d*(\.[0-9]\d*)*))?$/$2/')

                  if [ -z "$STAGE" ]; then
                    STAGE="prod"
                  fi

                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
                  echo "stage=$STAGE" >> $GITHUB_OUTPUT

    build:
        runs-on: ${{ matrix.os }}
        if: ${{ always() }}
        needs: [setup]
        strategy:
            matrix:
                os: [macos-11]
            fail-fast: true
        env:
            VERSION: ${{ needs.setup.outputs.version }}
            STAGE: ${{ needs.setup.outputs.stage || github.event.inputs.stage }}

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.4.2

            # Used to read the `binding.gyp` file from `@iota/wallet`
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal

            - name: Set deployment target (macOS)
              run: echo "MACOSX_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV # TODO: set this to 10.12 once rocksDB issue is fixed
              if: matrix.os == 'macos-11'

            - name: Enable verbose output for electron-builder (macOS/Linux)
              run: echo "DEBUG=electron-builder" >> $GITHUB_ENV
              if: matrix.os != 'windows-2019' && github.event.inputs.debugElectronBuilder && github.event.inputs.debugElectronBuilder == 'true'

            - name: Install dependencies
              # Increase network timeout threshold to reduce build failures on Windows
              run: yarn --network-timeout 1000000

            - name: Install Sentry CLI
              # Yarn has issues putting binaries in the PATH on Windows
              run: npm i -g @sentry/cli
              if: ${{ startsWith(github.ref, 'refs/tags/desktop') && matrix.os == 'windows-2019' }}

            - name: Set productName
              run: node scripts/fix-productName.js
              working-directory: packages/desktop

            - name: Bundle desktop JS
              run: yarn build:${STAGE}
              working-directory: packages/desktop
              shell: bash
              env:
                  HARDCODE_NODE_ENV: true
                  SENTRY: ${{ startsWith(github.ref, 'refs/tags/desktop') }}
                  SENTRY_DSN: ${{ secrets.SENTRY_DSN_PROD_DESKTOP }}
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

            - name: Build Electron app (macOS)
              run: yarn compile:${STAGE}:mac
              env:
                  CSC_LINK: ${{ secrets.MAC_CERT_BASE64 }}
                  CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
                  FIREFLY_APPLE_ID: ${{ secrets.APPLE_ID }}
                  FIREFLY_APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
              working-directory: packages/desktop
              if: matrix.os == 'macos-11'

            - name: Compute checksums (macOS)
              run: for i in `ls | grep 'firefly-desktop*'` ; do shasum -a 256 $i | awk {'print $1'} > $i.sha256 ; done
              working-directory: packages/desktop/out
              if: matrix.os == 'macos-11'

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: firefly-desktop-${{ matrix.os }}
                  path: |
                      packages/desktop/out/firefly-desktop*
                      packages/desktop/out/shimmer*
